site_name: Mobile Access Gateway
repo_url: https://github.com/ahdis/MobileAccessGateway
theme:
  name: material
  logo: assets/mag_logo.png
  favicon: assets/favicon-256x256.png
  palette:
    scheme: mag
  features:
    - content.code.annotate
extra_css:
  - stylesheets/extra.css
nav:
  - 1. Home: index.md
  - 2. Features: features.md
  - 3. Endpoints: endpoints.md
  - 4. EPR Integration: integration-primary-system.md
  - 5. Testing: testing.md
  - 6. Container: docker.md
  - 7. Changelog: changelog.md
  - 8. Configuration: configuration.md
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: ["docs/snippets"]
  - pymdownx.tabbed:
      alternate_style: true
