site_name: MobileAccessGateway
repo_url: https://github.com/i4mi/MobileAccessGateway
theme:
  name: material
  logo: assets/mag_logo.png
  favicon: assets/favicon-256x256.png
  palette:
    scheme: mag
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Features: features.md
  - Changelog: changelog.md
