# General configuration of the Mobile Access Gateway

mag:
#  iua:
#    idp:
#      name: idp-ehealthsuisse
#      metadata-url: https://ehealthsuisse.ihe-europe.net/metadata/idp-metadata.xml
#      key-store: example-client-certificate.jks
#      key-store-password: a1b2c3
#      key-alias: gateway
#      key-password: a1b2c3
#      tls-key-alias:
#      tls-key-password:
#    sp:
#      entity-id: mobileaccessgateway.pagekite.me
#      disable-code-challenge: false
#    clients:
#      oauthdebugger:
#        secret: demosecret
#        redirect: https://oauthdebugger.com/debug
#      playground:
#        secret: secret
#        redirect: https://developers.google.com/oauthplayground
  audit:
    audit-enabled: false

# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#server-properties

server:
  max-http-header-size: 15000
  http:
    port: 9090 # Application listening port for HTTP. Remove line to disable.
  servlet:
    session:
      timeout: 15m # Session duration must give the users enough time to fill out identity provider login pages
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: info

camel:
  springboot:
    main-run-controller: true

# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#core-properties
spring:
  application:
    name: mobile-access-gateway
#  web:
#    resources:
#      add-mappings: false