# General configuration of the Mobile Access Gateway

mag:
  baseurl: http://localhost
  client-ssl:
    enabled: true
    key-store: example-client-certificate.jks    
    key-store-password: a1b2c3
    cert-alias: gateway    
  xds:
    https: true
    iti-18:     
      url: ehealthsuisse.ihe-europe.net:10443/xdstools7/sim/default__ahdis/reg/sq         
    iti-43:      
      url: ehealthsuisse.ihe-europe.net:10443/xdstools7/sim/default__ahdis/rep/ret          
    iti-41:      
      url: ehealthsuisse.ihe-europe.net:10443/xdstools7/sim/default__ahdis/rep/prb
    retrieve:
      url: http://localhost:9090/camel/xdsretrieve
      repositoryUniqueId: 1.1.4567332.1.2    
  pix:
    https: true
    iti-45:      
      url: ehealthsuisse.ihe-europe.net:10443/PAMSimulator-ejb/PIXManager_Service/PIXManager_PortType      
    iti-44:      
      url: ehealthsuisse.ihe-europe.net:10443/PAMSimulator-ejb/PIXManager_Service/PIXManager_PortType      
    iti-47:            
      url: ehealthsuisse.ihe-europe.net:10443/PAMSimulator-ejb/PDQSupplier_Service/PDQSupplier_PortType
    oids:
      sender: 1.3.6.1.4.1.21367.2017.2.2.108      
      receiver: 1.3.6.1.4.1.12559.11.25.1.10                 
      query: 1.3.6.1.4.1.21367.2017.2.1.104
      custodian: 1.3.6.1.4.1.21367.2017.2.5.83
  iua:
     idp:
        name: idp-ehealthsuisse
        metadata-url: https://ehealthsuisse.ihe-europe.net/metadata/idp-metadata.xml
        key-store: example-client-certificate.jks    
        key-store-password: a1b2c3
        key-alias: gateway         
        key-password: a1b2c3
     sp:
        entity-id: mobileaccessgateway.pagekite.me
     ap:        
        url: https://ehealthsuisse.ihe-europe.net/STS
        wsdl: https://ehealthsuisse.ihe-europe.net/STS?wsdl                
     clients:
        oauthdebugger:
           secret: demosecret
           redirect: https://oauthdebugger.com/debug
        playground:
           secret: secret
           redirect: https://developers.google.com/oauthplayground

  audit:
    audit-enabled: true 
    audit-tls-enabled: false
    # in productive system audit-source-id must be same as audit-enterprise-site-id
    audit-enterprise-site-id: 1.3.6.1.4.1.21367.2017.2.7.109
    audit-repository-host: 147.135.232.177
    audit-repository-port: 3001
    audit-repostiory-transport: UDP             

# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#server-properties

server:
  max-http-header-size: 10000
  ssl:
    key-store: classpath:example-server-certificate.p12    
    key-store-password: a1b2c3    
    key-store-type: pkcs12
    key-alias: server             
  port: 9091 # Application listening port for HTTPS
  http:
    port: 9090 # Application listening port for HTTP. Remove line to disable.

logging:
  level:
    root: info
camel:
  springboot:
    xmlRoutes: false
    main-run-controller: true

# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#core-properties
spring:
  application:
    name: mobile-access-gateway
