apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-access-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-access-gateway
  template:
    metadata:
      labels:
        app: mobile-access-gateway
    spec:
      volumes:    
      - name: mobile-access-gateway-config-volume
        configMap:        
          name: mobile-access-gateway-configmap
      - name: mobile-access-gateway-secret-volume
        secret:
          secretName: mobile-access-gateway-secret
      containers:
      - name: mobile-access-gateway
        image: europe-west6-docker.pkg.dev/ahdis-ch/ahdis/mag:v070        
        resources:
          requests:
            memory: "0.6Gi"
        ports:
        - containerPort: 9090
        - containerPort: 9091
        volumeMounts:        
        - name: mobile-access-gateway-config-volume
          mountPath: /config
        - name: mobile-access-gateway-secret-volume
          mountPath: /secret
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 20
          periodSeconds: 2
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          initialDelaySeconds: 20
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-access-gateway-service
spec:
  type: NodePort
  ports:
  - port: 9090
    name: http
    targetPort: 9090
    nodePort: 30090
  - port: 9091
    name: https
    targetPort: 9091
    nodePort: 30091
  selector:
    app: mobile-access-gateway
---