name: Publish documentation
on:
  workflow_dispatch: # On manual trigger
  push:
    branches:
      - "master"
    paths:
      - "docs/**"

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install mkdocs
        run: pip install -r requirements.txt

      - name: Build static documentation and deploy
        run: mkdocs gh-deploy --force
        # https://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages
